# Try running:
#
# ansible-playbook -i inventory module_1.5.yaml
#
---
- name: Examine the bomb disposal training dummy
  hosts: bomb_disposal_training_dummy

  tasks:
    - name: Get the state of the dummy
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: dummy
        
    - name: Show the dummy's state
      ansible.builtin.debug:
        var: bomb_state

    - name: Press the reset button if the tone knob is 4 or less
      # Use the ansiblebombsquad.defuse.press_button module to press
      # the 'reset' button, but only if the current value of the tone
      # knob is 4 or less

    - name: Cut the red wire if the blue wire is already cut
      # Use the ansiblebombsquad.defuse.cut_wire module to cut
      # the 'red' wire, but only if the 'blue' wire is already
      # cut (wire's state is True)
        
    - name: Cut the blue wire if the volume is set to 1 AND the timer is a gold watch
      # Use the ansiblebombsquad.defuse.cut_wire module to cut
      # the 'blue' wire, but only if the current value of the volume
      # knob is 1 and the timer_type is 'gold watch'

    - name: Get the final state of the dummy
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: dummy
        
    - name: Show the dummy's state
      ansible.builtin.debug:
        var: bomb_state

    - name: Assert that the blue wire has been cut
      # Use the ansible.builtin.assert module to check that the new
      # state of the bomb indicates that the blue wire is cut

    - name: Assert that the red wire has not been cut
      # Use the ansible.builtin.assert module to check that the new
      # state of the bomb indicates that the red wire is not cut