# Try running:
#
# ansible-playbook -i inventory module_2.1.yaml
#
---
- name: Defuse the Tsar Bomba bomb
  hosts: tsar_bomba

  # TODO: Make this readable by the rest of the team
  tasks:
    - name: Reset the bomb state
      ansiblebombsquad.defuse.reset_bomb_state:
        bomb_name: tsar_bomba

    - name: Get the state of the bomb
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: tsar_bomba

    - name: Show the bomb's state
      ansible.builtin.debug:
        var: bomb_state

    - name: Get the timer_type of the bomb as a var
      ansible.builtin.set_fact:
        _timer_type: "{{ bomb_state.state.timer_type }}"

    - name: Ensure bomb-defuser-bot-2000 configuration staging file is up to date
      ansible.builtin.template:
        src: templates/bomb-defuser-bot-2000.conf.j2
        dest: /tmp/defuser.conf.staging
        mode: "0755"
      vars:
        bomb_name: tsar_bomba

    - name: Ensure the staging configuration is copied to the runtime configuration
      ansible.builtin.command: "cp /tmp/defuser.conf.staging /tmp/defuser.conf"
      register: _cp_result
      failed_when: _cp_result.rc != 0
      changed_when: _cp_result.rc == 0
      environment:
        BOMB_NAME: tsar_bomba

    - name: Cut all of the wires on the bomb
      ansiblebombsquad.defuse.cut_wire:
        bomb_name: tsar_bomba
        colour: "{{ item.key }}"
      loop: "{{ bomb_state.state.wires | dict2items }}"

    - name: Get the final state of the dummy
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: tsar_bomba

    - name: Show the dummy's state
      ansible.builtin.debug:
        var: bomb_state

    - name: Assert that each of the wires has been cut
      ansible.builtin.assert:
        that:
          - item.value == True
      loop: "{{ bomb_state.state.wires | dict2items }}"
