# Try running:
#
# ansible-playbook -i inventory module_2.1.yaml
#
---
- name: Defuse a bomb with an "alarm clock" timer
  hosts: bomb_robot
  vars:
    _bomb_name: "bartholemew_the_strangler"

  # TODO: Turn this into reusable code
  tasks:
    - name: Reset the bomb state
      ansiblebombsquad.defuse.reset_bomb_state:
        bomb_name: "{{ _bomb_name }}"

    - name: Get the state of the bomb
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: "{{ _bomb_state }}"

    - name: Show the bomb's state
      ansible.builtin.debug:
        var: bomb_state

    - name: Get the timer_type of the bomb as a var
      ansible.builtin.set_fact:
        _timer_type: "{{ bomb_state.state.timer_type }}"

    - name: Ensure that the timer is an alarm_clock
      ansible.builtin.assert:
        that:
          - _timer_type == "alarm_clock"

    # To defuse the bomb, we need to:
    #  1) Turn the alarm_mode knob to "3"
    #  2) Cut the red and blue wires
    #  3) Press the "test_alarm" button
    - name: Ensure the alarm_mode knob is set to 3
      ansiblebombsquad.defuse.turn_knob:
        bomb_name: "{{ _bomb_name }}"
        knob: "alarm_mode"
        setting: "3"

    - name: Ensure the red and the blue wires on the bomb are cut
      ansiblebombsquad.defuse.cut_wire:
        bomb_name: "{{ _bomb_name }}"
        colour: "{{ item.key }}"
      loop:
        - red
        - blue

    - name: Press the "test_alarm" button
      ansiblebombsquad.defuse.press_button:
        bomb_name: "{{ _bomb_name }}"
        button: "test_alarm"

    - name: Get the final state of the bomb
      ansible.builtin.include_role:
        name: ansiblebombsquad.defuse.get_bomb_state
      vars:
        bomb_name: "{{ _bomb_name }}"

    - name: Show the bomb's state
      ansible.builtin.debug:
        var: "{{ _bomb_name }}"
